language: node_js
services:
- elasticsearch
addons:
  sonarcloud:
    organization: loopingz-github
node_js:
- '8'
before_script:
- sleep 15
script:
- npm run test
after_success:
- sonar-scanner
before_deploy:
- npm run build
deploy:
  provider: npm
  email: rcattiau@loopingz.com
  skip_cleanup: true
  tag: next
  on:
    tags: true
  api_key:
    secure: Q3zXhT9TlfjwXtZMT1JEJSDDsv0QXtxZrN3AiH1YhB0Y/OGmRxy4lY/5EPR6L34foYv0MkDnVO3+CXgwWpm0CWw4Au9AC4wgtqbZSGmgflJPr8vR1krvaEubPS0l5xb+nEElhAF9VEfK04ZYycYrLaV58BaahGMAMFBtww2ADrPLFonyqBQIUlvkcSGDl1gBfsGx2xs36tPQrpjMZlRAPCyOsU4sqJZD8pUYI1yGdTEjRyBE3ISt1JA1+05kyTU4dsyEfS74PqIz0uEqi4ol4FLhO4XEi2H2WIltC1cjAYeHziuvmy66SizAh1j674lowbx3WO0KrSlamnZiKnoCykTRTzlRm/Rdx2CTAXhk/hjb3Ai3Rm2R0KKXrUlkikEnTC2ovQE4ZaKCfh7CBgJ8CJbi62B3vIjd4BMR7Ljurt5zECn71HirmZq9nKsFdpdzCEw/ToIHaCBOvyVFdx2Hrisc1tedZ3baU+aK/NPviL4RQjRipBIrVJGswPpTQyv+TTane0FCtTHBHwyquTMo2eok2PZDewHzSVxyUbcVAxMPnzFZEdKawA2wLnsBk5JbihlJGChxEb2k756Mhz+5Lrh7YL/wl0aTnIpqrdtuuc0r71h2CyelTK2jB6UfRLTwS/QevZ5N0JBeXbgnBATxDdgrWxVlgckLH5OfiN2yPBo=
